services:
  wvr-lite:
    build: .
    container_name: "wvr-lite"
    ports:
      - 8080:8080
    networks:
      - mcp-network
    volumes:
      - ./logs:/app/logs
    #   - database:/app/db

networks:
  mcp-network:
    external: true
    name: mcp_mcp-network

# volumes:
#   database: